version: '3'

services:
    
    mysqldb:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: users
        volumes: 
        - ./data/pg:/var/lib/mysql
    
    user:
        build: .
        restart: always
        ports:
            - 8070:8070
        depends_on: 
            - mysqldb
         

    
    